// <auto-generated>
//   This file is generated by `code/tools/action-space-export/emit_csharp.py`.
//
//   DO NOT EDIT BY HAND. Edits will be overwritten by the next codegen run.
//
//   Source of truth: code/digimon-engine/src/action/space.rs
//   Regenerate:
//     cargo run -p action-space-export | python code/tools/action-space-export/emit_csharp.py --out DCGO/Assets/Scripts/Script/Recording/ActionSpace.cs
//
//   CI verifies the committed copy matches the regenerated output. If you
//   see a CI failure pointing at this file, run the regenerate command and
//   commit the diff.
// </auto-generated>

namespace Digimon.Recording
{
    /// <summary>
    /// Action-space layout mirrored from the Rust engine's
    /// <c>digimon_engine::action::space</c> module. Used by the DCGO
    /// <c>ActionEncoder</c> to translate in-client decisions into the
    /// 2192-ID action space the Rust engine and trained policies share.
    /// </summary>
    public static class ActionSpace
    {

        /// Schema version stamped into recordings produced by the DCGO mod. The Rust replay harness
        /// rejects recordings whose schema version exceeds the version it was built against.
        public const uint SCHEMA_VERSION = 1;

        /// Total action-space size. Used to size mask buffers.
        public const int ACTION_SPACE_SIZE = 2192;

        // ── Single-ID constants ─────────────────────────────────────

        public const ushort BREEDING_SELECTION_TARGET = 99;
        public const ushort BREEDING_SELECT_PLAYER_0 = 14;
        public const ushort BREEDING_SELECT_PLAYER_1 = 15;
        public const ushort BREEDING_SOURCE_CARRIERS = 2;
        public const ushort BREEDING_TARGET = 14;
        public const ushort CONCEDE_GAME = 93;
        public const ushort FIELD_EFFECT_SLOT_FOR_MAIN = 2;
        public const ushort FIELD_EFFECT_SLOT_FOR_OVERCLOCK = 0;
        public const ushort HAND_MAIN_LIMIT = 30;
        public const ushort HATCH = 60;
        public const ushort MAX_REVEALED = 10;
        public const ushort MAX_SECURITY = 10;
        public const ushort MOVE_FROM_BREEDING = 61;
        public const ushort PASS = 62;
        public const ushort PLAY_FIRST = 94;
        public const ushort PLAY_SECOND = 95;
        public const ushort REPLACEMENT_ACCEPT = 59;
        public const ushort SECURITY_TARGET = 14;
        public const ushort TRASH_MAIN_LIMIT = 45;

        // ── Stride / cardinality constants ─────────────────────────

        public const ushort EFFECTS_PER_PERMANENT = 10;
        public const ushort FIELDS_PER_HAND = 15;
        public const ushort MAX_FIELD_SLOTS = 14;
        public const ushort SOURCES_PER_FIELD = 12;
        public const ushort TARGETS_PER_ATTACKER = 15;

        // ── Range bounds (half-open [start, end)) ──────────────────

        public const ushort ATTACK_START = 100;
        public const ushort ATTACK_END   = 400;
        public const ushort BREEDING_SOURCE_SELECT_START = 2168;
        public const ushort BREEDING_SOURCE_SELECT_END   = 2192;
        public const ushort DIGIVOLVE_START = 400;
        public const ushort DIGIVOLVE_END   = 1000;
        public const ushort DNA_DIGIVOLVE_START = 63;
        public const ushort DNA_DIGIVOLVE_END   = 93;
        public const ushort FIELD_EFFECT_START = 1000;
        public const ushort FIELD_EFFECT_END   = 1150;
        public const ushort HAND_EFFECT_START = 30;
        public const ushort HAND_EFFECT_END   = 60;
        public const ushort PLAY_HAND_START = 0;
        public const ushort PLAY_HAND_END   = 30;
        public const ushort SEL_MY_SECURITY_START = 40;
        public const ushort SEL_MY_SECURITY_END   = 50;
        public const ushort SEL_OPP_SECURITY_START = 50;
        public const ushort SEL_OPP_SECURITY_END   = 60;
        public const ushort SEL_REVEAL_START = 30;
        public const ushort SEL_REVEAL_END   = 40;
        public const ushort SOURCE_SELECT_START = 2000;
        public const ushort SOURCE_SELECT_END   = 2168;
        public const ushort TRASH_EFFECT_START = 1150;
        public const ushort TRASH_EFFECT_END   = 1195;

        // ── Encoder helpers (mirror Rust encode_* functions) ──────

        /// Mirrors Rust `encode_attack`. Returns the encoded action ID. Throws
        /// ArgumentOutOfRangeException if attacker >= 14 or target >= 15.
        public static ushort EncodeAttack(int attacker, int target)
        {
            if ((uint)attacker >= 14) throw new System.ArgumentOutOfRangeException(nameof(attacker));
            if ((uint)target >= 15) throw new System.ArgumentOutOfRangeException(nameof(target));
            return (ushort)(100 + attacker * 15 + target);
        }

        /// Mirrors Rust `encode_digivolve`. Returns the encoded action ID. Throws
        /// ArgumentOutOfRangeException if handIndex >= 30 or fieldIndex >= 15.
        public static ushort EncodeDigivolve(int handIndex, int fieldIndex)
        {
            if ((uint)handIndex >= 30) throw new System.ArgumentOutOfRangeException(nameof(handIndex));
            if ((uint)fieldIndex >= 15) throw new System.ArgumentOutOfRangeException(nameof(fieldIndex));
            return (ushort)(400 + handIndex * 15 + fieldIndex);
        }

        /// Mirrors Rust `encode_field_effect`. Returns the encoded action ID. Throws
        /// ArgumentOutOfRangeException if permIndex >= 14 or effectIndex >= 10.
        public static ushort EncodeFieldEffect(int permIndex, int effectIndex)
        {
            if ((uint)permIndex >= 14) throw new System.ArgumentOutOfRangeException(nameof(permIndex));
            if ((uint)effectIndex >= 10) throw new System.ArgumentOutOfRangeException(nameof(effectIndex));
            return (ushort)(1000 + permIndex * 10 + effectIndex);
        }

        /// Mirrors Rust `encode_source_select`. Returns the encoded action ID. Throws
        /// ArgumentOutOfRangeException if fieldIndex >= 14 or sourceIndex >= 12.
        public static ushort EncodeSourceSelect(int fieldIndex, int sourceIndex)
        {
            if ((uint)fieldIndex >= 14) throw new System.ArgumentOutOfRangeException(nameof(fieldIndex));
            if ((uint)sourceIndex >= 12) throw new System.ArgumentOutOfRangeException(nameof(sourceIndex));
            return (ushort)(2000 + fieldIndex * 12 + sourceIndex);
        }

        /// Mirrors Rust `encode_breeding_source_select`. Returns the encoded action ID. Throws
        /// ArgumentOutOfRangeException if carrierOwner >= 2 or sourceIndex >= 12.
        public static ushort EncodeBreedingSourceSelect(int carrierOwner, int sourceIndex)
        {
            if ((uint)carrierOwner >= 2) throw new System.ArgumentOutOfRangeException(nameof(carrierOwner));
            if ((uint)sourceIndex >= 12) throw new System.ArgumentOutOfRangeException(nameof(sourceIndex));
            return (ushort)(2168 + carrierOwner * 12 + sourceIndex);
        }

    }
}

